### ISSUE TITLE
Provide a constructor for `Hash`

### ISSUE THREAD

**Issue by tailhook** [oconnor663/blake2_simd#25]
It would be nice to be able to construct `Hash` from string or bytes to compare it to the computed hash, instead of comparing the string/bytes representation.

Optional `serde` support would be even better.

**Comment by oconnor663** [comment]
I forgot that the `Hash` type in these crates were missing the `From<[u8; 32]>` impl. I should probably just add it.

The [version of this type](https://docs.rs/blake3/1.1.0/blake3/struct.Hash.html) in the `blake3` crate has more methods, and probably all of them would make sense here too. I wonder if it's time to consider splitting it out into a standalone crate, which could be shared by many different crates? On the other hand, would we rather keep the property that comparing a BLAKE2 hash to a BLAKE3 hash with `==` is a type error? Not sure.

Also I'm sure the RustCrypto folks (who maintain the `digest` crate) have some thoughts about this. @tarcieri is working on merging implementations from this repo into their `blake2` crate also. Tony, have you guys ever considered defining a shared `Hash` type or something like that? I know the `Digest` trait works with `GenericArray`, but now that const generics don't require any sort of hacks, it might make sense to define a new type (with constant-time equality, hexification, and so on).

**Comment by oconnor663** [comment]
@tailhook what do you think of https://github.com/oconnor663/blake2_simd/pull/26 as a first step?

**Comment by tailhook** [comment]
Yes. This is a good start! At least I can do all other stuff (parse from string) myself now.

> On the other hand, would we rather keep the property that comparing a BLAKE2 hash to a BLAKE3 hash with `==` is a type error?

I like this idea. It's better than having hash type by length (i.e. Hash32/Hash64), and clearer than using generic `ConstTimeCmpArray<u8, 32>`.

**Comment by tarcieri** [comment]
> Tony, have you guys ever considered defining a shared Hash type or something like that?

This is what we presently have in the `digest` crate:

https://docs.rs/digest/0.9.0/digest/type.Output.html

> I know the Digest trait works with GenericArray, but now that const generics don't require any sort of hacks...

Unfortunately `min_const_generics` are not sufficient for our use cases. See ongoing discussion here:

https://github.com/RustCrypto/hashes/issues/30

**Comment by tarcieri** [comment]
>  define a new type (with constant-time equality, hexification, and so on).

This sounds a bit more like the current `crypto_mac::Output` newtype:

https://docs.rs/crypto-mac/0.11.1/crypto_mac/struct.Output.html

I believe @newpavlov has plans to unify `digest` and `crypto_mac`, although I don't know the plans regarding the `Output` types specifically.

**Comment by oconnor663** [comment]
I just landed the PR above. As part of publishing these changes, I'm leaning towards just tagging these crates v1.0.0 and calling everything stable. (Which wouldn't rule out any future enhancements to the `Hash` type, of course.) @tarcieri would that be alright with you? Any impact to `blake2` from doing that?

**Comment by oconnor663** [comment]
Published `blake2b_simd`, `blake2s_simd`, and `blake2_bin` version 1.0.0.
